// Generated by CoffeeScript 1.10.0
(function() {
  var render;

  window.addEventListener("load", function() {
    return window.requestAnimationFrame(function() {
      if (location.hash) {
        return render({
          id: location.hash.replace("#", "")
        });
      }
    });
  });

  document.on("click", "a[href^='#']", function(event, hyperlink) {
    return render({
      id: hyperlink.href.toString().split("#")[1]
    });
  });

  document.on("mousemove", "body > div[id]", function(event, div) {
    var baseURL, id;
    id = div.id;
    baseURL = location.toString().split("#")[0];
    if (location.hash !== ("#" + id)) {
      history.replaceState({}, "", baseURL + "#" + id);
    }
    return render({
      id: id
    });
  });

  document.on("DOMContentLoaded", function() {
    return window.sections = Array.apply(null, document.querySelectorAll("body > div[id]")).reverse();
  });

  document.on("scroll", function(event) {
    var baseURL, div, id;
    baseURL = location.toString().split("#")[0];
    div = window.sections.find(function(div) {
      var distance;
      distance = div.offsetTop - window.scrollY - window.pointer.y;
      return distance < 1;
    });
    if (div === void 0) {
      if (location.hash !== void 0) {
        history.replaceState({}, "", "" + baseURL);
      }
      return render({});
    } else {
      id = div.id;
      if (location.hash !== ("#" + id)) {
        history.replaceState({}, "", baseURL + "#" + id);
      }
      return render({
        id: id
      });
    }
  });

  render = function(data) {
    var elem, i, j, len, len1, ref, ref1;
    ref = document.querySelectorAll("*.selected");
    for (i = 0, len = ref.length; i < len; i++) {
      elem = ref[i];
      elem.classList.remove("selected");
    }
    if (data.id) {
      ref1 = document.querySelectorAll("a[href='#" + data.id + "']");
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        elem = ref1[j];
        elem.classList.add("selected");
      }
      return document.getElementById(data.id).classList.add("selected");
    }
  };

}).call(this);
