// Generated by CoffeeScript 1.8.0
(function() {
  var getImage;

  document.on("DOMContentLoaded", function() {
    document.query("img[width][height]").forEach(function(img) {
      var canvas;
      canvas = document.createElement("canvas");
      canvas.width = img.getAttribute("width");
      canvas.height = img.getAttribute("height");
      img.removeAttribute("width");
      img.removeAttribute("height");
      return img.src = canvas.toDataURL();
    });
    return document.query("video[width][height]:not([poster])").forEach(function(video) {
      var canvas;
      canvas = document.createElement("canvas");
      canvas.width = video.getAttribute("width");
      canvas.height = video.getAttribute("height");
      video.removeAttribute("width");
      video.removeAttribute("height");
      return video.poster = canvas.toDataURL();
    });
  });

  window.addEventListener("load", function() {
    return Function.delay(1..second(), function() {
      document.query("img[data-src]").forEach(function(img) {
        return getImage(img.getAttribute("data-src"), function(imageURL) {
          img.src = img.getAttribute("data-src");
          return img.classList.add("loaded");
        });
      });
      return document.query("video[data-poster]").forEach(function(video) {
        return getImage(video.getAttribute("data-poster"), function(imageURL) {
          video.poster = imageURL;
          return video.classList.add("loaded");
        });
      });
    });
  });

  getImage = function(src, callback) {
    var img;
    img = document.createElement("img");
    img.onload = function() {
      return callback(src);
    };
    return img.src = src;
  };

}).call(this);
